name: al_muslim
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  awesome_notifications: ^0.9.3+1
  awesome_snackbar_content: ^0.1.3
  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  easy_container: ^1.0.4+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  flutter_qiblah: ^3.0.3
  flutter_screenutil: ^5.9.3
  font_awesome_icon_class: ^0.0.6
  geocoding: ^3.0.0
  geolocator: 11.1.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  internet_connection_checker: ^2.0.0
  intl: ^0.19.0
  just_audio: ^0.9.39
  linear_progress_bar: ^1.1.2
  liquid_progress_indicator_v2: ^0.5.0
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  quran: ^1.3.0
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
  fonts:
    - family: IBMPlex
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
    - family: notoCofi
      fonts:
        - asset: assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
