name: al_muslim
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  build_runner: ^2.4.12
  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  flutter_qiblah: ^3.0.3
  font_awesome_icon_class: ^0.0.6
  geocoding: ^3.0.0
  geolocator: 11.1.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.19.0
  just_audio: ^0.9.39
  linear_progress_bar: ^1.1.2
  lottie: ^3.1.2
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/

    - assets/icons/
  fonts:
    - family: IBMPlex
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
    - family: notoCofi
      fonts:
        - asset: assets/fonts/NotoKufiArabic-VariableFont_wght.ttf
          # - asset: fonts/Schyler-Italic.ttf
          # style: italic
